config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  get "home/index"
  root to: "home#index"

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy] do
    resources :comments
    resources :likes
  end

  get "search" => "search#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_hash_tags, on: :create
  belongs_to :user

  has_one_attached :image
  validate :image_presence

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map { |name| name.gsub("#", "") }
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    post = comment.post
    comment.destroy
    redirect_to post_path(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    if !already_liked?
      @post = Post.find(params[:post_id])
      @post.likes.create!(user_id: current_user.id)
      redirect_to root_path
    end
  end

  def destroy
    like = current_user.likes.find(params[:id])
    post = like.post
    like.destroy
    redirect_to root_path
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:show]

  def create
    p = Post.create(post_params)
    flash.notice = "Post Created Sucessfully"
    redirect_to root_path
  end

  # GET /posts/id
  def show
    @post = Post.find(params[:id])
  end

  #DELETE /posts/id
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    flash.alert = "Post Deleted Sucessfully!"
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:description, :image).merge(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(resource)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET user/id/show
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="max-w-3xl w-full mx-auto relative bg-white shadow rounded-lg">
  <div class="flex w-full flex-col p-4 md:p-6">
    <%= form_for Post.new do |f| %>
    <%= f.text_area :description , placeholder: "I am super excited <3", class:"appearance-none block w-full bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-4 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"%>
    <div class="md:flex justify-between items-center">
      <div class="md:w-2/3">
        <label class="w-1/2 text-center cursor-pointer truncate bg-primary-100 border border-dashed border-primary-600 p-3 items-center font-semibold rounded text-sm hover:text-primary-600 hover:bg-primary-200 hover:border-primary-500 flex-grow" for="post_image">
          <span class="w-full">
            <span class="truncate">
              <%= f.file_field :image ,class:"" %>
            </span>
          </span>
        </label>
      </div>
      <div class="w-1/3 mt-2 md:mt-0">
        <%= f.submit "Create Post", class:"w-full btn btn-large btn-primary mt-2 md:mt-0"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="max-w-3xl mx-auto justify-center">
  <div>
    <% @posts.each do |post| %>
    <div class="rounded-lg bg-white shadow border p-4 mt-4 rounded">
      <div class="flex w-full items-center">
        <%= link_to  user_path(post.user) do%>
        <% if post.user.avatar.attached? %>
        <%= image_tag  post.user.avatar ,class:"rounded-full my-2 h-10 w-10 shadow"  %>
        <%else%>
        <%= image_tag("dp.png", :alt => "Default DP", class:"rounded-full my-2 h-10 w-10 shadow" ) %>
        <%end%>
        <%end%>
        <%= link_to user_path(post.user) do %>
        <%if post.user.username?%>
        <h3 class="text-xl  font-bold px-2 py-4"><%=  post.user.username%></h3>
        <%else%>
        <h3 class="text-xl  font-bold px-2 py-4">anonymous_user</h3>
        <%end%>
        <%end%>
      </div>
      <%= link_to post_path(post) do %>
      <% if post.image.attached? %>
      <div class="mx-auto">
        <%= image_tag post.image ,class:"relative w-full object-contain h-std rounded-lg shadow-lg"%>
      </div>
      <% end %>
      <%end%>


      <% already_liked = post.likes.find{|like| like.user_id == current_user&.id} %>
      <div class="flex items-center py-1 mt-3">
        <div class="flex items-center">
          <%if already_liked%>
          <%= button_to post_like_path(post,already_liked), method: :delete  do  %>
          <i class="fas fa-heart text-primary-700 text-xl"></i>
          <%end%>
          <%else%>
          <%= button_to post_likes_path(post), method: :post  do  %>
          <i class="far fa-heart text-primary-700 text-xl"></i>
          <%end%>
          <%end%>
          <h3 class="ml-2 text-sm text-gray-600 "><%= post.likes.count %><%=post.likes.count <= 1 ? " like" : " likes"%></h3>
        </div>
        <div class="ml-2 flex items-center">
          <i class="fas fa-comment-alt text-primary-700 text-lg"></i>
          <h3 class="ml-2 text-sm text-gray-600 "><%=  post.comments.count %><%= post.comments.count <= 1 ? " Comment" : " Comments"%></h3>
        </div>
      </div>
      <h3 class="mt-2 text-sm font-bold "><%= post.description%></h3>
      <% post.comments.last(2).each do |comment| %>

      <%if comment.user.username?%>
      <h3 class="text-xs font-bold py-2 border-t border-primary-100 "><%=  comment.user.username%>:
        <span class="font-normal">
          <%= comment.body%>
        </span>
      </h3>
      <%else%>
      <h3 class="text-xs font-bold py-2 border-t border-primary-100 ">anonymous_user:
        <span class="font-normal">
          <%= comment.body%>
        </span>
      </h3>
      <%end%>
      <%end%>
      <%= link_to post_path(post), class: "block w-full text-center rounded-lg text-primary-500 text-xs font-semibold focus:outline-none hover:text-primary-400"  do  %>
      <span class="inline-block bg-gray-100 px-2">Show All</span>
      <%end%>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% post = @post %>

<div class="max-w-3xl mx-auto">
  <div class="rounded-lg bg-white shadow border p-4 mt-4 rounded">
    <div class="flex w-full items-center">
      <%= link_to  user_path(post.user) do%>
      <% if post.user.avatar.attached? %>
      <%= image_tag  post.user.avatar ,class:"rounded-full my-2 h-10 w-10 shadow"  %>
      <%else%>
      <%= image_tag("dp.png", :alt => "Default DP", class:"rounded-full my-2 h-10 w-10 shadow" ) %>
      <%end%>
      <%end%>
      <%= link_to user_path(post.user) do %>
      <%if post.user.username?%>
      <h3 class="text-xl font-bold px-2 py-4"><%=  post.user.username%></h3>
      <%else%>
      <h3 class="text-xl font-bold px-2 py-4">anonymous_user</h3>
      <%end%>
      <%end%>
    </div>
    <%= link_to post_path(post) do %>
    <% if post.image.attached? %>
    <div class="mx-auto">
      <%= image_tag post.image ,class:"relative  w-full object-contain h-std rounded-lg shadow-lg"%>
    </div>
    <% end %>
    <%end%>


    <% already_liked = post.likes.find{|like| like.user_id == current_user&.id} %>
    <div class="flex justify-between items-center">
      <div class="flex items-center py-1 mt-3">
        <div class="flex items-center">
          <%if already_liked%>
          <%= button_to post_like_path(post,already_liked), method: :delete  do  %>
          <i class="fas fa-heart text-primary-700 text-xl"></i>
          <%end%>
          <%else%>
          <%= button_to post_likes_path(post), method: :post  do  %>
          <i class="far fa-heart text-primary-700 text-xl"></i>
          <%end%>
          <%end%>
          <h3 class="ml-2 text-sm text-gray-600 "><%= post.likes.count %><%=post.likes.count <= 1 ? " like" : " likes"%></h3>
        </div>
        <div class="ml-4 flex items-center">
          <i class="fas fa-comment-alt text-primary-700 text-lg"></i>
          <h3 class="ml-2 text-sm text-gray-600 "><%=  post.comments.count %><%= post.comments.count <= 1 ? " Comment" : " Comments"%></h3>
        </div>
      </div>

      <% if @post.user_id == current_user&.id %>
      <%= button_to post_path(@post), method: :delete, class:"hover:bg-primary-100 px-2 py-1 rounded text-primary-700 font-semibold", data: { confirm: 'Are you sure?' }  do %>
      <i class="fas fa-trash-alt text-primary-700 text-lg mr-2"></i>
      Delete Post
      <%end%>
      <%end%>
    </div>
    <h3 class="mt-2 text-sm font-bold "><%= post.description%></h3>
    <% post.comments.each do |comment| %>
    <div class="flex justify-between items-center border-t border-primary-100 ">
      <div>
        <%if comment.user.username?%>
        <h3 class="text-xs font-bold py-2 border-t border-primary-100 "><%=  comment.user.username%>:
          <span class="font-normal">
            <%= comment.body%>
          </span>
        </h3>
        <%else%>
        <h3 class="text-xs font-bold py-2 border-t border-primary-100 ">anonymous_user:
          <span class="font-normal">
            <%= comment.body%>
          </span>
        </h3>
        <%end%>
      </div>
      <% if comment.user_id  == current_user&.id  %>
      <%= link_to post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="ml-2 fas fa-trash-alt text-primary-700"></i>
      <% end %>
      <%end%>
    </div>
    <%end%>


    <div class="flex w-full flex-col">
      <%= form_for Comment.new , url: post_comments_path(@post)  do |f| %>
      <%= f.text_field :body , placeholder: "Enter the Comment...", class:"appearance-none block w-full bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-4 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"%>
      <%= f.submit "Add Comment", class:"btn btn-primary mt-2 md:mt-0"%>
      <% end %>
    </div>

  </div>
</div>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/users/edit.html.erb
<div class="container mx-auto px-3 py-8 max-w-5xl">
  <div class="bg-white shadow rounded-lg">
    <div class="px-4 py-5 ">
      <div class="flex  flex-col md:flex-row md:items-center">
        <div class="w-full md:w-1/3 pr-4">
          <h3 class="text-lg text-center font-black text-primary-700">Edit your Profile</h3>
          <p class="mt-1 text-sm text-center text-primary-600">Update the information to make your public profile classy!</p>
        </div>
        <div class=" mt-5 md:mt-0 w-full md:w-2/3 ">
          <%=form_with model: current_user do |f| %>
          <div class="mx-auto p-2  ">
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :name ,class:" text-lg font-bold text-primary-800" %>
              <%= f.text_field :name , placeholder: "Enter your name", class:"sm:w-2/3 w-full appearance-none bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :username ,class:" text-lg font-bold text-primary-800 " %>
              <%= f.text_field :username ,placeholder: "Enter your username", class:"sm:w-2/3 w-full appearance-none  bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :display_picture ,class:" sm:w-1/3 w-full text-lg font-bold text-primary-800" %>
              <%= f.file_field :avatar , class:" sm:w-2/3 w-full text-center cursor-pointer truncate bg-primary-100 border border-dashed border-primary-600 p-3 items-center font-semibold rounded text-sm hover:text-primary-600 hover:bg-primary-200 hover:border-primary-500 flex-grow" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :website ,class:" text-lg font-bold text-primary-800" %>
              <%= f.text_field :website , placeholder: "Enter your website url",class:"sm:w-2/3 w-full appearance-none  bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :bio ,class:" text-lg font-bold text-primary-800" %>
              <%= f.text_area :bio ,cols: 23,placeholder: "Enter the bio",  class:"sm:w-2/3 w-full appearance-none  bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :email ,class:" text-lg font-bold text-primary-800" %>
              <%= f.text_field :email ,placeholder: "Enter your email", class:"sm:w-2/3 w-full appearance-none  bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :phone ,class:" text-lg font-bold text-primary-800" %>
              <%= f.text_field :phone ,placeholder: "Enter your phone number", class:"sm:w-2/3 w-full appearance-none  bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500" %>
            </div>
            <div class="flex justify-between mt-2 flex-col sm:flex-row">
              <%= f.label :gender ,class:"text-lg font-bold text-primary-800" %>
              <%= f.text_field :gender ,placeholder: "Male/Female", class:"sm:w-2/3 w-full appearance-none  bg-white text-primary-900 font-normal border border-primary-400 rounded py-3 px-4 mb-1 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"%>
            </div>
            <div class="flex justify-end mt-4">
              <%= f.submit "Submit", class:"btn btn-primary btn-large sm:w-2/3 w-full" %>

            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="bg-white rounded-lg shadow min-h-screen">
  <div class="max-w-3xl mx-auto">
    <div class="flex flex-col sm:flex-row items-center sm:justify-around  px-6 py-4">
      <% if @user.avatar.attached?%>
      <div>
        <%= image_tag  @user.avatar, class:"rounded-full my-5 h-32 w-32 shadow-lg  " %>
      </div>
      <%else%>
      <%= image_tag("dp.png", :alt => "Default DP", class:"rounded-full my-5 h-32 w-32 shadow-lg " ) %>
      <%end%>
      <div class="py-3">
        <div class="flex justify-between">
          <%if @user.name?%>
          <h3 class="text-black text-3xl font-bold text-primary-700 py-3 pr-3"><%=@user.name%></h3>
          <%else%>
          <h3 class="text-black text-3xl font-bold text-primary-700 py-3 pr-3">Anonymous User</h3>
          <%end%>
          <% if @user.id == current_user&.id%>
          <a href="<%= edit_user_path(@user) %>" class="pt-5">
            <button class=" btn btn-primary-ghost"> Edit Profile</button>
          </a>
          <%end%>
        </div>
        <div class="flex justify-between">
          <div class="pr-4">
            <h5 class="font-black text-primary-900"><%=@posts.count %> <span class="font-normal ">Posts</span></h5>
          </div>
          <div class="pr-4">
            <h5 class="font-black text-primary-900">324 <span class="font-normal">Followers</span></h5>
          </div>
          <div>
            <h5 class="font-black text-primary-900">412 <span class="font-normal">Following</span></h5>
          </div>
        </div>
        <h4 class="pt-1 text-primary-900">
          <%=@user.bio%>
        </h4>
        <a href="https://<%=@user.website%>" class="text-blue-700 pt-1" target="blank"><%=@user.website%></a>
        <div class="flex flex-col sm:flex-row justify-between ">
          <div class="flex mt-2 ">
            <i class="animate-pulse fas fa-map-marker-alt text-primary-500 text-lg"> </i>
            <p class="ml-2 text-sm font-bold text-primary-900">Location </p>
          </div>
          <div class="flex mt-2 ml-2">
            <i class="animate-pulse fas fa-birthday-cake text-primary-500 text-lg"></i>
            <p class="ml-2 text-sm font-bold text-primary-900">Birthday </p>
          </div>
          <div class="flex mt-2 ml-2">
            <i class="animate-pulse fas fa-calendar-alt text-primary-500 text-lg"></i>
            <p class="ml-2 text-sm font-bold text-primary-900">Joined <%=@user.created_at.strftime("%B %Y")%> </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr class="border-primary-100 mt-6" />
  <div class=" flex flex-wrap  max-w-3xl mx-auto py-4 justify-start">
    <% @posts.each do |post| %>
    <% if post.image.attached?%>
    <%= link_to post_path(post), class: "p-4" do %>
    <%= image_tag post.image ,class:"relative rounded-lg shadow-lg  object-cover h-56 w-56 bg-auto"%>
    <div class="flex mt-2 ">
      <div class="flex  ">
        <i class="fas fa-heart text-primary-400 text-sm"></i>
        <h3 class="ml-2 text-xs text-gray-600 "><%= post.likes.count %><%=post.likes.count <= 1 ? " like" : " likes"%></h3>
      </div>
      <div class="flex ml-4">
        <i class="fas fa-comment-alt text-primary-400 text-sm"></i>
        <h3 class="ml-2 text-xs text-gray-600 "><%=  post.comments.count %><%= post.comments.count <= 1 ? " Comment" : " Comments"%></h3>
      </div>
    </div>


    <%end%>
    <%end%>
    <%end%>
  </div>
</div>